### ISSUE TITLE
Provide Jinja2 and SQL combined syntax highlighting

### ISSUE THREAD

**Issue by lewish** [tada-science/dataform-tracking#28]
Currently model files are highlighted for SQL, and macro files highlighted for Jinja.

Should be possible to provide a combined syntax highlighting plugin within codemirror.

Should customise highlighting depending on the data warehouse you are using (redshift, bigquery, snowflake...)

**Comment by G2H** [comment]
See example for atom here. https://github.com/fishtown-analytics/atom-dbt
