### ISSUE TITLE
Pretty Print Compilation Errors

### ISSUE THREAD

**Issue by chrisgoddard** [tada-science/dataform-tracking#59]
It would be great if any compilation errors could be formatted so they were easier to read. Right now they're all in-line like this:

<img width="1595" alt="screen shot 2018-08-01 at 10 28 22 am" src="https://user-images.githubusercontent.com/4922472/43538041-cd74bb94-9575-11e8-8e7b-8c6669a6de42.png">

**Comment by lewish** [comment]
Added some structure to these, however most of the content is just the original file contents which I've decided to omit, instead just providing the name and type of the file where the error was caused.

Will look into getting line numbers out, but this isn't currently provided by the Jinja compilation exception.
